openapi: 3.0.0
info:
  title: TextIndexer-v1
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /indexer/v1/document:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Documents'
              examples:
                example-1:
                  value:
                    docs:
                      - id: skdfhaergezkrghkergkerg
                        location: 'https://www.gutenberg.org/files/1342/1342-0.txt'
                        encoding: utf-8
                        language: english
                        title: Pride and Prejudice
                        author: Jane Austen
                        status: pending
      operationId: get-indexer-v1-document
      parameters:
        - schema:
            type: integer
          in: query
          name: skip
        - schema:
            type: integer
          in: query
          name: limit
      description: Get a list of document records
    post:
      summary: ''
      operationId: post-indexer-v1-document
      responses:
        '204':
          description: No Content
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentRecord'
            examples:
              example-1:
                value:
                  location: 'https://www.gutenberg.org/files/1342/1342-0.txt'
                  encoding: utf-8
                  language: english
                  title: Pride and Prejudice
                  author: Jane Austen
      description: Add a document record
  '/indexer/v1/document/{doc_id}':
    parameters:
      - schema:
          type: string
        name: doc_id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentRecord'
              examples:
                example-1:
                  value:
                    id: skdfhaergezkrghkergkerg
                    location: 'https://www.gutenberg.org/files/1342/1342-0.txt'
                    encoding: utf-8
                    language: english
                    title: Pride and Prejudice
                    author: Jane Austen
                    status: pending
      operationId: get-indexer-v1-document-doc
      parameters: []
      description: Get the document record
  '/indexer/v1/document/{doc_id}/index':
    parameters:
      - schema:
          type: string
        name: doc_id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentIndex'
              examples:
                example-1:
                  value:
                    id: sdlfnalscnawecwavvaSV
                    paragraphs:
                      - start: 0
                        length: 250
                        tokens:
                          - token: the
                            start: 0
                    source: ZLVNDFLBKRBAVZVDHASKDVH
      operationId: get-indexer-v1-document-doc_id-index
      parameters: []
      description: Get the index record related to the document
  '/indexer/v1/document/{doc_id}/full':
    parameters:
      - schema:
          type: string
        name: doc_id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentRecord'
              examples:
                example-1:
                  value:
                    id: skdfhaergezkrghkergkerg
                    location: 'https://www.gutenberg.org/files/1342/1342-0.txt'
                    encoding: utf-8
                    language: english
                    title: Pride and Prejudice
                    author: Jane Austen
                    text: All the text
      operationId: get-indexer-v1-document-doc_id-full
      parameters: []
      description: Get the document with the full text enabled
  /indexer/v1/words:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Words'
              examples:
                example-1:
                  value:
                    count: 1
                    word:
                      - id: asdlcnaiecvnwaeclevvwe
                        word: the
                        encoding: utf-8
                        language: english
                        references:
                          - index: sadlfiawlenflwaec
                            source: sadlfiawlenflwaec
                            paragraph: 0
                            start: 0
                            end: 2
                            sentence: 0
                            word: 0
      operationId: get-indexer-v1-words
      description: ''
      parameters:
        - schema:
            type: integer
          in: query
          name: skip
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: boolean
          in: query
          name: reverse
components:
  schemas:
    Word:
      title: Word
      type: object
      properties:
        id:
          type: string
        word:
          type: string
        encoding:
          type: string
        language:
          type: string
        references:
          type: array
          items:
            type: object
            properties:
              index:
                type: string
              paragraph:
                type: integer
              start:
                type: integer
        reference_count:
          type: integer
    DocumentIndex:
      title: Document
      type: object
      properties:
        id:
          type: string
        paragraphs:
          type: array
          items:
            type: object
            properties:
              start:
                type: integer
              length:
                type: integer
              tokens:
                type: array
                items:
                  type: object
                  properties:
                    token:
                      type: string
                    start:
                      type: integer
        source:
          type: string
          description: Source Document Record
      x-examples:
        example-1:
          id: sdlfnalscnawecwavvaSV
          paragraphs:
            - start: 0
              length: 250
              tokens:
                - token: the
                  start: 0
          source: ZLVNDFLBKRBAVZVDHASKDVH
    DocumentRecord:
      description: ''
      type: object
      x-examples:
        example-1:
          id: skdfhaergezkrghkergkerg
          location: 'https://www.gutenberg.org/files/1342/1342-0.txt'
          encoding: utf-8
          language: english
          title: Pride and Prejudice
          author: Jane Austen
          text: All the text
          status: indexed
      properties:
        location:
          type: string
          minLength: 1
        encoding:
          type: string
          minLength: 1
        language:
          type: string
          minLength: 1
        title:
          type: string
          minLength: 1
        author:
          type: string
          minLength: 1
        id:
          type: string
        text:
          type: string
        status:
          type: string
          enum:
            - pending
            - retrieving
            - processing
            - indexed
      required:
        - location
        - title
    Documents:
      title: Documents
      type: object
      properties:
        count:
          type: integer
        documents:
          $ref: '#/components/schemas/DocumentRecord'
    Words:
      title: Words
      type: object
      properties:
        count:
          type: integer
        words:
          $ref: '#/components/schemas/Word'
